services:
  frontend:
    build:
      context: ./frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080

  backend:
    build:
      context: ./backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authentication
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
