[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1"
sea-orm = "1"
axum = "0.7.7"
serde = "1.0.210"
tera = "1"
lettre = "0.11.9"

[dev-dependencies]
reqwest = { version = "0.12.8", features = ["json", "blocking"] }